const eventType = {
    UPCOMING_EVENT: "UPCOMING_EVENT",
    COMPLETED_EVENT: "COMPLETED_EVENT",
    CANCELED_EVENT: "CANCELLED_EVENT",
    ONGOING_EVENT : "ONGOING_EVENT"
}

module.exports = eventType;